name: StegoGuard URL Image Scan

on:
  push:
  workflow_dispatch:

jobs:
  image-forensics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create images folder
        run: mkdir -p images

      - name: Download image from link
        run: |
          curl -L "https://share.google/RR1lQToK7B0RCYfKE" -o images/url_image.jpg
          ls -lh images
          file images/url_image.jpg

      - name: Run StegoGuard scanner
        run: python scanner.py
