name: StegoGuard URL Image Scan

on:
  push:
  workflow_dispatch:

jobs:
  image-forensics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare images folder
        run: |
          mkdir -p images
          rm -f images/*

      - name: Download image from URL
        run: |
          curl -fL "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyNtszXR0k_IRff9aXPylipo3l-I-8vzopNP9FFobi3VkQCxSpXqbABdc6&s=10" -o images/url_image.jpg
          ls -lh images
          file images/url_image.jpg

      - name: Run StegoGuard scanner
        run: python scanner.py
